# See https://houndci.com/configuration for help.
haml:
  # config_file: .haml-style.yml
  enabled: true
javascript:
  # config_file: .javascript-style.json
  enabled: false
  # ignore_file: .javascript_ignore
eslint:
  enabled: true
  config_file: .eslintrc
  ignore_file: .eslintignore
ruby:
  config_file: .rubocop.yml
  enabled: true
scss:
  # config_file: .scss-style.yml
  enabled: true
