# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'spec/support/capybara_webkit.rb'
