# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'
    - 'config/routes.rb'
    - 'config/environments/*'

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'spec/support/capybara_webkit.rb'
